## Tipo arrendatarios [/catalogos/tipoArrendatarios]

### tipoArrendatarios [GET]
    Obtiene el listado de los arrendatarios

+ Response 200 (application/json)
<!-- include(responseTipoArrendatarios.json) -->
