## Caracteristicas Propiedad  [/propiedad/caracteristicas/{idPropiedad}]

### caracteristicasPropiedad [PUT]

+ Parameters
    + idPropiedad (number, required) - Id de la propiedad


+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l


    + Body
<!-- include(request.json) -->

+ Response 200 (application/json)
<!-- include(response.json) -->
       
+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
        {
            "error": {
                "mensaje": "Internal Server Error"
            },
            "result": null
        }
