FORMAT: 1A
HOST: http://localhost:3050

# Group Catálogos
<!-- include(services/catalogos/banco/banco.apib) -->
<!-- include(services/catalogos/banco/bancos.apib) -->
<!-- include(services/catalogos/categoria/categoria.apib) -->
<!-- include(services/catalogos/categoria/categorias.apib) -->
<!-- include(services/catalogos/estatus/estatus.apib) -->
<!-- include(services/catalogos/estatus/estatus2.apib) -->
<!-- include(services/catalogos/modulo/modulo.apib) -->
<!-- include(services/catalogos/modulo/modulos.apib) -->
<!-- include(services/catalogos/nacionalidad/nacionalidades.apib) -->
<!-- include(services/catalogos/nacionalidad/nacionalidad.apib) -->
<!-- include(services/catalogos/regimen/regimen.apib) -->
<!-- include(services/catalogos/regimen/regimenes.apib) -->
<!-- include(services/catalogos/sucursal/sucursales.apib) -->
<!-- include(services/catalogos/sucursal/sucursal.apib) -->
<!-- include(services/catalogos/tipoCaracteristica/tipoCaracteristica.apib) -->
<!-- include(services/catalogos/tipoCaracteristica/tipoCaracteristicas.apib) -->
<!-- include(services/catalogos/tipoDato/tipoDatos.apib) -->
<!-- include(services/catalogos/tipoDato/tipoDato.apib) -->
<!-- include(services/catalogos/tipoImagen/tipoImagen.apib) -->
<!-- include(services/catalogos/tipoImagen/tipoImagenes.apib) -->
<!-- include(services/catalogos/tipoMultimedia/tipoMultimedia.apib) -->
<!-- include(services/catalogos/tipoMultimedia/tipoMultimedias.apib) -->
<!-- include(services/catalogos/tipoPersona/tipoPersonas.apib) -->
<!-- include(services/catalogos/tipoPersona/tipoPersona.apib) -->
<!-- include(services/catalogos/tipoPropiedad/tipoPropiedad.apib) -->
<!-- include(services/catalogos/tipoPropiedad/tipoPropiedades.apib) -->
<!-- include(services/catalogos/tipoReferencia/tipoReferencia.apib) -->
<!-- include(services/catalogos/tipoReferencia/tipoReferencias.apib) -->
<!-- include(services/catalogos/tipoRelacion/tipoRelacion.apib) -->
<!-- include(services/catalogos/tipoRelacion/tipoRelaciones.apib) -->
<!-- include(services/catalogos/tipoUsuario/tipoUsuario.apib) -->
<!-- include(services/catalogos/tipoUsuario/tipoUsuarios.apib) -->



# Group Session
<!-- include(services/session/login/login.apib) -->
<!-- include(services/session/logout/logout.apib) -->
<!-- include(services/session/account/changePassword.apib) -->
 

# Group Propiedades
<!-- include(services/propiedades/generales/generales.apib) -->
<!-- include(services/propiedades/direccionPropiedad/direccionPropiedad.apib) -->
<!-- include(services/propiedades/caracteristicas/caracteristicas.apib) -->
<!-- include(services/propiedades/imagenesPropiedad/imagenesPropiedad.apib) -->
<!-- include(services/propiedades/videoPropiedad/videoPropiedad.apib) -->
<!-- include(services/propiedades/zona/zona.apib) -->
<!-- include(services/propiedades/busqueda/busqueda.apib) -->
<!-- include(services/propiedades/eliminar/eliminarPropiedad.apib) -->
<!-- include(services/propiedades/detalle/detallePropiedad.apib) -->


# Group Usuarios
<!-- include(services/usuario/crearUsuario/crearUsuario.apib) -->
<!-- include(services/usuario/infoBasica/infoBasica.apib) -->
<!-- include(services/usuario/info/usuarioInfo.apib) -->