FORMAT: 1A
HOST: http://localhost:3050

# Group Catálogos
<!-- include(services/catalogos/clasificacionCliente/personalidadJuridica.apib) -->
<!-- include(services/catalogos/clasificacionCliente/sectorCNBV.apib) -->
<!-- include(services/catalogos/datosGenerales/estadoCivil.apib) -->
<!-- include(services/catalogos/datosGenerales/pais.apib) -->
<!-- include(services/catalogos/datosGenerales/estado.apib) -->
<!-- include(services/catalogos/datosGenerales/lada.apib) -->
<!-- include(services/catalogos/identificacionCliente/tipoId.apib) -->
<!-- include(services/catalogos/promotor/promotor.apib) -->
<!-- include(services/catalogos/promotor/promotorOpCambios.apib) -->
<!-- include(services/catalogos/ppe/tipo.apib) -->
<!-- include(services/catalogos/ppe/relacion.apib) -->
<!-- include(services/catalogos/direccion/colonia.apib) -->
<!-- include(services/catalogos/direccion/localidadBANXICO.apib) -->
<!-- include(services/catalogos/direccion/localidadCNBV.apib) -->
<!-- include(services/catalogos/clasificacionRegulatoria/giroSector.apib) -->
<!-- include(services/catalogos/clasificacionRegulatoria/giroIndustry.apib) -->
<!-- include(services/catalogos/clasificacionRegulatoria/actividadBanxico.apib) -->
<!-- include(services/catalogos/clasificacionRegulatoria/actividadCNBV.apib) -->
<!-- include(services/catalogos/clasificacionRegulatoria/grupoEcoCNBV.apib) -->
<!-- include(services/catalogos/datosEmpleo/tipoEmpleo.apib) -->
<!-- include(services/catalogos/sucursal/sucursal.apib) -->

# Group Session
<!-- include(services/session/login/login.apib) -->
<!-- include(services/session/logout/logout.apib) -->
<!-- include(services/session/account/changePassword.apib) -->
<!-- include(services/session/account/me.apib) -->

# Group Generador Documentos
<!-- include(services/pdf-generator/generarDocumento/generarDocumento.apib) -->
<!-- include(services/pdf-generator/generatePDF/generatePDF.apib) -->

# Group Propiedades
<!-- include(services/propiedades/crearPropiedad.apib) -->