FORMAT: 1A
HOST: http://localhost:3050

# Group Catálogos
<!-- include(services/catalogos/banco/banco.apib) -->
<!-- include(services/catalogos/banco/bancos.apib) -->

# Group Session
<!-- include(services/session/login/login.apib) -->
<!-- include(services/session/logout/logout.apib) -->
<!-- include(services/session/account/changePassword.apib) -->
<!-- include(services/session/account/me.apib) -->

# Group Generador Documentos
<!-- include(services/pdf-generator/generarDocumento/generarDocumento.apib) -->
<!-- include(services/pdf-generator/generatePDF/generatePDF.apib) -->

# Group Propiedades
<!-- include(services/propiedades/crearPropiedad.apib) -->