## Eliminar Propiedad  [/propiedad/eliminarPropiedad/{idPropiedad}]

### eliminarPropiedad [DELETE]
Se encarga de eliminar la propiedad

+ Parameters
    + idPropiedad (number, required) - Id de la propiedad

+ Request Ejemplo
    
    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l
 
+ Response 200 (application/json)
    + Relation: 200: Ok

    + Body
<!-- include(response.json) -->

+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
       {
            "error": {
                "mensaje": "Internal Server Error"
            },
            "result": null
        }
