## Crear nuevo usuario [/usuario/crear]

### crearUsuario [POST]
Se encarga de crear un nuevo registro

+ Request Broker

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l

    + Body
<!-- include(broker.json) -->

+ Request Inquilino

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l
    
    + Body
<!-- include(inquilino.json) -->

+ Request propietario

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l
    
    + Body
<!-- include(propietario.json) -->

+ Response 200 (application/json)
    + Relation: 200: Ok

    + Body
        {
           "message": "Usuario creado"
        }

+ Response 400 (application/json)
 + Relation: 400: Error

 + Body
 {
    "error": {
        "mensaje": "string"
    }
     "result": "Problemas al crear usuario"
 }
+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
        {
            "error": {
                "mensaje": "string"
            },
            "result": null
        }
