## Tipo avales solidarios [/catalogos/tipoAvalesSolidarios]

### tipoAvalesSolidario [GET]
    Obtiene el listado de los avales solidarios

+ Response 200 (application/json)
<!-- include(responseTipoAvalesSolidarios.json) -->
