# GET /catalogos/tipoAvalesSolidario/{id}

+ Parameters
    + id (number, required) - Id del tipo de avales solidarios    

+ Response 200 (application/json)
<!-- include(responseTipoAvalesSolidario.json) -->

