## Tipo referencias [/catalogos/tipoReferencias]

### tipoReferencias [GET]
    Obtiene el listado de los tipos de referencia

+ Response 200 (application/json)
<!-- include(responseTipoReferencias.json) -->
