## Personalidades Jurídicas [/cat/personalidadJuridica]

### personalidadesJuridicas [GET]
    Obtiene el listado de personalidades jurídicas

+ Response 200 (application/json)
<!-- include(personalidadJuridica.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
