## Sector CNBV [/cat/sectorCNBV]

### sectorCNBV [GET]
    Obtiene el listado de Sectores CNBV

+ Response 200 (application/json)
<!-- include(sectorCNBV.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
