## Disponibilidad broker por mes [/disponibilidad/broker]

### disponibilidadBrokerMes [POST]

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l


    + Body
<!-- include(requestDisponibilidad.json) -->

+ Response 200 (application/json)
<!-- include(response.json) -->
       
+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
        {
            "error": {
                "mensaje": "Internal Server Error"
            },
            "result": null
        }
