## Giro - INDUSTRY [/cat/giroIndustry]

### giroIndustry [POST]
    Obtiene el listado de industrias

+ Request Ejemplo
    + Attributes 
        + idSector(number) - id del sector, obtenido de /cat/giroSector

+ Response 200 (application/json)
<!-- include(giroIndustry.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
