## Tipo datos [/catalogos/tipoDatos]

### tipoDatos [GET]
    Obtiene el listado de los datos

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l

+ Response 200 (application/json)
<!-- include(responseTipoDatos.json) -->
