## Tipo de empleo [/cat/tipoEmpleo]

### tipoEmpleo [GET]
    Obtiene el listado de tipos de empleo

+ Response 200 (application/json)
<!-- include(tipoEmpleo.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
