## sucursal [/cat/sucursal]

### sucursal [GET]
    Obtiene el listado de sucursales

+ Response 200 (application/json)
<!-- include(sucursal.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
