## Relación PPE [/cat/relacionPPE]

### relacionPPE [GET]
    Obtiene el listado de eelaciónes PPE

+ Response 200 (application/json)
<!-- include(relacion.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->