## Tipo de exposición política [/cat/tipoPPE]

### tipoPPE [GET]
    Obtiene el listado de tipos de exposición política

+ Response 200 (application/json)
<!-- include(tipo.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
s