## Tipo caracteristicas [/catalogos/tipoCaracteristicas]

### tipoCaracteristicas [GET]
    Obtiene el listado de las caracteristicas

+ Response 200 (application/json)
<!-- include(responseTipoCaracteristicas.json) -->
