# GET /catalogos/tipoCaracteristica/{id}

+ Parameters
    + id (number, required) - Id de la caracteristica   

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l


+ Response 200 (application/json)
<!-- include(responseTipoCaracteristica.json) -->

