## Tipo arrendadores [/catalogos/tipoArrendadores]

### tipoArrendadores [GET]
    Obtiene el listado de los arrendadores

+ Response 200 (application/json)
<!-- include(responseTipoArrendadores.json) -->
