## Tipo multimedias [/catalogos/tipoMultimedias]

### tipoMultimedias [GET]
    Obtiene el listado de los tipos de multimedia

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l

+ Response 200 (application/json)
<!-- include(responseTipoMultimedias.json) -->
