## Tipo multimedias [/catalogos/tipoMultimedias]

### tipoMultimedias [GET]
    Obtiene el listado de los tipos de multimedia

+ Response 200 (application/json)
<!-- include(responseTipoMultimedias.json) -->
