## Regimenes [/catalogos/regimenes]

### regimenes [GET]
    Obtiene el listado de las regimenes

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l


+ Response 200 (application/json)
<!-- include(responseRegimenes.json) -->
