## País [/cat/pais]

### pais [GET]
    Obtiene el listado de estados civiles

+ Response 200 (application/json)
<!-- include(pais.json) -->

+ Response 200 (application/json)
<!-- include(../errors/nodata.json) -->

+ Response 500 (application/json)
<!-- include(../errors/500.json) -->
