## Tipo relaciones [/catalogos/tipoRelaciones]

### tipoRelaciones [GET]
    Obtiene el listado de los tipos de relaciones

+ Response 200 (application/json)
<!-- include(responseTipoRelaciones.json) -->
