## Info basica  [/usuario/infoBasica]

### usuarioInfoBasica[GET]

+ Request Ejemplo

    + Body
        {
            
        }

+ Response 200 (application/json)
    + Relation: 200: Ok

    + Body
<!-- include(infoBasicaResponse.json) -->
       
+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
        {
            "error": {
                "mensaje": "Internal Server Error"
            },
            "result": null
        }
