## Actualizar citas Broker por mes  [/citas/broker]

### actualizarBroker [PUT]

+ Request Ejemplo

    + Headers
        Authorization: YWxhZGRpbjpvcGVuc2VzYW1l


    + Body
<!-- include(actualizarCitaBrokerRequest.json) -->

+ Response 200 (application/json)
<!-- include(actualizarCitaBrokerResponse.json) -->
       
+ Response 500 (application/json)
    + Relation: 500: Error
    
    + Body
        {
            "error": {
                "mensaje": "Internal Server Error"
            },
            "result": null
        }
